title       = "powo"
baseURL     = "https://powo-cli.tamnd.com/"
description = "A command line for powo."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/powo-cli"
